// Copyright (c) 2026, Ali-Eimaan. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// SKELETON — declarations only. See .deepseek/08_TUBE.md.
//
// Tube MPC-CBF: robust safety for
//     x_{k+1} = f(x_k, u_k) + w_k,   w_k in W (compact, contains 0)
// via a nominal trajectory z, an ancillary feedback u = v + K (x - z), and an
// offline RPI set Omega bounding the error e = x - z. Nominal state/input
// constraints and the DCBF condition are all tightened with Omega so that
// safety holds for the true state, not merely the nominal one.

#ifndef MPC_CBF_UNIFIED__TUBE_MPC_CBF_SOLVER_HPP_
#define MPC_CBF_UNIFIED__TUBE_MPC_CBF_SOLVER_HPP_

#include <Eigen/Dense>

#include <memory>
#include <string>
#include <vector>

#include "mpc_cbf_unified/disturbance_sets.hpp"
#include "mpc_cbf_unified/mpc_cbf_solver.hpp"

namespace mpc_cbf_unified
{

/// How the DCBF condition is made robust against the tube.
enum class TightenMode
{
  kSupportFunction = 0,  ///< Exact for affine h: subtract h_Omega(-grad h).
  kLipschitz,            ///< General h: subtract L_h * max{||e|| : e in Omega}.
  kNone                  ///< Nominal CBF only — unsafe, kept for the ablation plot.
};

/// Tube-specific configuration; mirrors config/tube_mpc_params.yaml.
struct TubeConfig
{
  Zonotope disturbance_set;       ///< W in the state space (dimension nx).
  Eigen::MatrixXd K;              ///< nu x nx ancillary gain; A + B K must be Schur.
  bool compute_gain_from_lqr{true};   ///< If true, K is overwritten by discreteLqrGain().
  Eigen::VectorXd lqr_Q;          ///< size nx, used only when compute_gain_from_lqr.
  Eigen::VectorXd lqr_R;          ///< size nu, ditto.

  double rpi_epsilon{1.0e-3};     ///< Accuracy of the mRPI outer approximation.
  int rpi_max_iterations{100};
  int rpi_max_generators{64};     ///< Zonotope order reduction cap during the iteration.

  TightenMode tighten_mode{TightenMode::kSupportFunction};
  double lipschitz_h{1.0};        ///< L_h, used when tighten_mode == kLipschitz.

  /// kNone (nominal, un-tightened CBF) exists only for the A8 ablation. Refuse
  /// to initialise with it unless this flag is set, so the unsafe mode cannot
  /// be reached from a launch file by accident (08_TUBE.md §8.4).
  bool allow_unsafe_ablation{false};

  /// Recompute Omega whenever the linearisation point moves further than this
  /// (0 disables re-computation; Omega is then computed once in initialize()).
  double relinearisation_threshold{0.0};
};

/// One tube-MPC-CBF solve. `u_applied` already contains the ancillary term.
struct TubeMpcCbfSolution
{
  SolverStatus status{SolverStatus::kNotInitialized};

  Eigen::VectorXd u_applied;   ///< nu; v_0 + K (x_0 - z_0), saturated to U.
  Eigen::VectorXd v0;          ///< nu; nominal input before the ancillary term.
  Eigen::MatrixXd z_pred;      ///< nx x (N+1) nominal states.
  Eigen::MatrixXd v_pred;      ///< nu x N nominal inputs.

  /// Tightened barrier value at each nominal stage, obstacle-major layout:
  /// index k * n_obs + j. Negative means the tube touches the obstacle.
  std::vector<double> robust_cbf_values;
  /// Amount subtracted from each nominal h by the tightening, same layout.
  std::vector<double> tightening;

  SolverDiagnostics diagnostics;

  bool usable() const;
};

/// Robust variant of MpcCbfSolver. Owns its own acados solver instance
/// (generated by codegen/generate_tube_solver.py) plus the offline RPI data.
///
/// Threading and allocation contract are identical to MpcCbfSolver.
class TubeMpcCbfSolver
{
public:
  TubeMpcCbfSolver(
    const MpcConfig & mpc_config, const CbfConfig & cbf_config, const TubeConfig & tube_config);
  ~TubeMpcCbfSolver();

  TubeMpcCbfSolver(const TubeMpcCbfSolver &) = delete;
  TubeMpcCbfSolver & operator=(const TubeMpcCbfSolver &) = delete;
  TubeMpcCbfSolver(TubeMpcCbfSolver &&) noexcept;
  TubeMpcCbfSolver & operator=(TubeMpcCbfSolver &&) noexcept;

  /// Validates configs, computes K (if requested) and the RPI set, tightens the
  /// state/input bounds, and allocates the acados solver. This is the expensive
  /// call — expect O(100 ms) — and it must never run inside the control loop.
  /// Returns false when A + B K is not Schur stable, when W is unbounded or does
  /// not contain the origin, or when the tightened input set is empty.
  bool initialize();

  bool isInitialized() const;

  /// Solve for the current *true* state. The nominal state z_0 is chosen per
  /// §8.5 (initial-state strategy), not simply set to x0.
  TubeMpcCbfSolution solve(
    const Eigen::VectorXd & x0,
    const std::vector<ObstacleState> & obstacles);

  void setReference(const Eigen::VectorXd & x_ref);
  void setReferenceTrajectory(const Eigen::MatrixXd & x_ref_traj);
  void reset();

  /// The RPI set computed in initialize(). Empty before initialisation.
  const Polytope & rpiSet() const;
  /// The ancillary gain actually in use (LQR result when computed).
  const Eigen::MatrixXd & ancillaryGain() const;
  /// Nominal state bounds after tightening: X (-) Omega.
  const Polytope & tightenedStateSet() const;
  /// Nominal input bounds after tightening: U (-) K Omega.
  const Polytope & tightenedInputSet() const;

  /// Scalar subtracted from h_j(z_k) to make the nominal DCBF condition imply
  /// the true one. Exposed so tests and the notebook can plot the tube margin.
  double tighteningFor(
    const Eigen::VectorXd & z, const ObstacleState & obstacle) const;

  /// Offline check that the certificate actually holds for the configured
  /// (A_cl, W, Omega). Called by initialize() and by the robustness gtest.
  bool verifyInvariance(double tol = 1e-6) const;

private:
  struct Impl;
  std::unique_ptr<Impl> impl_;

  /// Support function of the certified RPI set: the exact zonotope when F_s was
  /// never order-reduced (verifyInvariance then certifies the zonotope via the
  /// closed-form certificate), otherwise the polytope (LP fallback). The margin
  /// and the tightened sets must be consistent with the certificate, and this
  /// keeps the per-solve hot path LP-free (§8.4).
  double omegaSupport(const Eigen::VectorXd & direction) const;
};

const char * toString(TightenMode mode);
bool parseTightenMode(const std::string & name, TightenMode & out);

}  // namespace mpc_cbf_unified

#endif  // MPC_CBF_UNIFIED__TUBE_MPC_CBF_SOLVER_HPP_
